name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v4

      - name: Update manifest version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          jq --arg version "$VERSION" '.version = $version' \
            custom_components/grow_room_manager/manifest.json > tmp.json
          mv tmp.json custom_components/grow_room_manager/manifest.json

      - name: Create zip
        run: |
          cd custom_components/grow_room_manager
          zip -r ../../grow_room_manager.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: grow_room_manager.zip
